<article class="logo">
    <div class="font-white">
        <h1>
            <?php \AeonRush\Test::hi($this) ?>
        </h1>
        <div>
        </div>
    </div>
</article>
<article class="full-width mobile-valign-top">
    <div>
        <?php new \Fragment\Home('index', $this, 'Simple, stylish, fast!'); ?>
        <?php new \Fragment\Home('index', $this, 'Modern, progressive!'); ?>
        <?php new \Fragment\Home('index', $this, 'Eva'); ?>
    </div>
</article>
